//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutU
    {
        public int Id { get; set; }
        public string title { get; set; }
        public string Description { get; set; }
        public string AboutImage { get; set; }
        public string İconimg { get; set; }
    }
}
